"""new fields in user table

Revision ID: 556d34424f66
Revises: ad92421ff40b
Create Date: 2020-05-24 17:00:06.513454

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '556d34424f66'
down_revision = 'ad92421ff40b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
